#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'AlamofireExample' do
pod 'Alamofire', '~> 4.0'
#:git => 'https://github.com/Alamofire/Alamofire.git',
#:branch => 'swift3'
end
