# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'TestGitHubApi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestGitHubApi
    pod 'OctoKit.swift', :git => 'https://github.com/nerdishbynature/octokit.swift.git', :tag => '0.7.2'

end
